### ISSUE TITLE
Peerplay core gui does not display his version in the window tab.

### ISSUE THREAD

**Issue by Rodrigo-Ichaso** [peerplays-network/peerplays-core-gui#47]
![imagen](https://user-images.githubusercontent.com/14061030/60351353-99bc2f80-9993-11e9-8263-e8e6f848cbfe.png)
Can we have somenthing similar to easy view our current version.

**Comment by mseaward** [comment]
@Rodrigo-Ichaso Version number will be coming to the wallet soon 😄

**Comment by mseaward** [comment]
Closed with WAL-248-GPOS merge (v1.5.0-beta release)
